### ISSUE TITLE
Compiled library Cybele.Cybele.vo makes inconsistent assumptions

### ISSUE THREAD

**Issue by imel96** [clarus/cybele#5]
Hi again :)

I installed Cybele (1.3.0) with opam, when I tried it, coq throws this: "Error: Compiled library Cybele.Cybele.vo makes inconsistent assumptions over library Coq.Init.Logic."

I'm using coq that I downloaded myself (CoqIDE 8.5pl3), I hope that's Ok?

Here's the code that I use to test:

`Add LoadPath "~/.opam/default/lib/coq/user-contrib/".`
`Require Import Cybele.Cybele.`

**Comment by beta-ziliani** [comment]
CoqIDE will use its own version of Coq, while you're adding opam's version of Cybele. Either you download and compile and install Cybele, or install coqide from opam. In either case, you shouldn't need the Add LoadPath line.

**Comment by imel96** [comment]
Thank you. I tried running it with coqc that's installed from opam as you suggested and it works.

Also want to point out that I use `Require Import Cybele.Cybele.` not `Require Import Cybele.` as per example in http://cybele.gforge.inria.fr/get_started.html
